#!/bin/bash
set -e

CURRENT_DIR=$(cd -- "$(dirname -- "$0")" && cd .. && pwd)

. "$(dirname "$0")/../scripts/_.sh"
. "$(dirname "$0")/../scripts/_/generate_aliases.sh"

echo "Current directory: $CURRENT_DIR"

# Run install-local.sh
echo "Running install-local.sh..."
# bash "$CURRENT_DIR/install-local.sh"

# Append the output of aidd-help to README.md
# Replace "## Usage" until the end of the doc with the help
echo "Updating README.md with aidd-help output..."
sed -i '' '/## 🚀 Usage/,$d' "$CURRENT_DIR/README.md"

echo "Running aidd-help..."
echo "## 🚀 Usage" >> "$CURRENT_DIR/README.md"
echo "" >> "$CURRENT_DIR/README.md"
echo '```text' >> "$CURRENT_DIR/README.md"
bash "$CURRENT_DIR/scripts/aidd-help.sh" | sed 's/\\033\[[0-9;]*m//g' | sed 's/aidd-[^ ]*/`&`/g' >> "$CURRENT_DIR/README.md"
echo '```' >> "$CURRENT_DIR/README.md"

git add README.md

# Generate aliases.sh based on script names
echo "Generating aliases.sh..."
SCRIPTS_DIR="$CURRENT_DIR/scripts"
ALIASES_FILE="$CURRENT_DIR/aliases.sh"
generate_aliases "$SCRIPTS_DIR" "$ALIASES_FILE"

git add aliases.sh